### ISSUE TITLE
Cstring to LPCWSTR?

### ISSUE THREAD

**Issue by melMass** [planety/fsnotify#5]
Hi,

I was trying to find a replacement for fsmonitor (and since learned it doesn't work on windows anyway), but I couldn't make fsnotify work and don't know how to fix it in current nim:

```sh
base.nim(54, 37) Error: type mismatch
Expression: getFileAttributesW(addr(x))
  [1] addr(x): ptr WideCStringObj

Expected one of (first mismatch at [position]):
[1] proc getFileAttributesW(lpFileName: LPCWSTR): DWORD
```

This library is probably not actively maintained but any insights are welcome

**Comment by ringabout** [comment]
It should be fixed like this:
```nim
getFileAttributesW(cast[LPCWSTR](addr(x)))
```

**Comment by melMass** [comment]
Works! Thanks 
![image](https://github.com/planety/fsnotify/assets/7041726/d343f124-cd34-4162-bd96-ab140e6cb42d)
